#!/bin/bash
set -e

# Clear the environment
rm -fr build fff.h
mkdir build

# Configure the build
cd build
cmake -GNinja ../ || exit -1

# Build all targets
cmake --build . || exit -1

# Run all tests
ctest --output-on-failure
